### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by minimoz** [colyseus/docs#148]
**[Documentation typo]**

https://github.com/colyseus/docs/blob/b718261f47af5450072d7fb4f6c53f04ca5f6980/docs/state/schema.zh_CN.md?plain=1#L1221-L1227

Shouldn't it be :
```
inventory.items.set("left", new Weapon());
inventory.items.set("right", new Shield());
```
instead of:
```
inventory.set("left", new Weapon());
inventory.set("right", new Shield());
```

**Comment by endel** [comment]
Thank you for noticing @minimoz 🙌
