### ISSUE TITLE
Clarify `playersByClientId` on onMessage

### ISSUE THREAD

**Issue by endel** [colyseus/docs#22]
https://github.com/colyseus/docs/blob/master/docs/server/room.md#onmessage-client-data

**Comment by minviable** [comment]
Hey - do you want me to remove this from the doc? 
Or should i do an example ?

I largely prefer removing this reference RN
See PR https://github.com/colyseus/docs/pull/33

**Comment by minviable** [comment]
Sorry my markdown linking has let me down i am ashamed
