### ISSUE TITLE
Room example fails to build with Typescript

### ISSUE THREAD

**Issue by will-hart** [colyseus/docs#38]
The example here https://github.com/colyseus/docs/blob/master/docs/server/room.md#example-room doesn't build with Typescript. The error I get is 

```
Argument of type '{ map: typeof Player; }' is not assignable to parameter of type 'DefinitionType'
```

which occurs on the line 

```
@type({ map: Player})
```

I'm not sure if this is required but I can fix this by changing the `Player` class definition to extend `Schema`:

```
export class Player extends Schema {
  x: number = 0.11;
  y: number = 2.22;
}
```

**Comment by endel** [comment]
thanks for reporting @will-hart, just updated the docs
